name: Run RSI Bot
on:
  schedule:
    - cron: "0 */4 * * *" # Exécution toutes les 4 heures (6x/jour)
  workflow_dispatch:
permissions:
  contents: write # Permet de pousser les changements
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true # Nécessaire pour pousser les changements

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run RSI Bot
        env:
          CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python rsi_bot.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Affiche l'état des fichiers avant l'ajout
          echo "État des fichiers avant git add :"
          git status
    
          # Ajoute les fichiers
          git add tracked_cryptos.json last_update_id.txt
    
          # Affiche l'état des fichiers après l'ajout
          echo "État des fichiers après git add :"
          git status
      
          # Commit et push uniquement si des modifications sont détectées
          git diff --quiet || (git commit -m "Mise à jour des cryptos suivies" && git push)
